server:
  #Agent服务的端口，可以自行更改
  port: 7777

spring:
  application:
    name: apex-agent
  rabbitmq:
    #rabbitMQ的host地址（如果用体验版的mq，这个host改为部署体验版机器的ip）
    host: localhost
    #如果用体验版的mq，这里是5673
    port: 5673
    #MQ的用户名
    username: guest
    #MQ的密码
    password: guest
    #MQ的vHost
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3

sonic:
  chrome:
    # Agent机器上的chrome浏览器的driver路径，可以去http://npm.taobao.org/mirrors/chromedriver/下载
    path: C:\Program Files\Google\Chrome\Application\chromedriver.exe
  folder:
    # 如果跨网段，这个host和port改成后端的host和port
    url: http://localhost:8094/api/folder
  agent:
    # 替换为部署Agent机器的ipv4
    host: 127.0.0.1
    # 替换为前端新增Agent生成的key
    key: 29002272-4659-4808-a804-08ce3388b136
