server:
  port: 7777

spring:
  application:
    name: sonic-agent
  rabbitmq:
    host: localhost
    port: 5672
    username: sonic
    password: sonic
    virtual-host: sonic
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3

sonic:
  chrome:
    path: C:\Program Files\Google\Chrome\Application\chromedriver.exe
  folder:
    url: http://localhost:8094/api/folder
  agent:
    host: 127.0.0.1
    key: 29002272-4659-4808-a804-08ce3388b136
